name: metaquery_action
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py311h6a678d5_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py311h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h3c4dab8_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=7.1.1=gpl_hbbdf940_911
  - filelock=3.17.0=py311h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.44.3=h2b0a6b4_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=12.1.0=h15599e2_0
  - icu=75.1=he02047a_0
  - idna=3.7=py311h06a4308_0
  - intel-gmmlib=22.8.2=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jinja2=3.1.6=py311h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h6a678d5_0
  - level-zero=1.24.3=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libavif=1.3.0=h6395336_2
  - libavif16=1.3.0=h6395336_2
  - libcap=2.76=h0b2e76d_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_5
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=h27cfd23_1
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=6.31.1=h9ef548d_1
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libsystemd0=257.9=h996ca69_0
  - libtiff=4.7.1=h8261f1e_0
  - libudev1=257.9=h085a93f_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.2=he9a06e4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h7b6447c_0
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=hca5e8e5_1
  - libxml2=2.15.0=h26afc86_1
  - libxml2-16=2.15.0=ha9997c6_1
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.5=py311h06a4308_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.5.4=h26f9b46_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - pillow=11.0.0=py311h49e9ac3_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a8bead_2
  - pycparser=2.23=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.13=h9e4cc4f_0_cpython
  - python_abi=3.11=8_cp311
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py311h5eee18b_0
  - rav1e=0.7.1=h8fae777_3
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=py311h06a4308_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.22=h68140b3_0
  - setuptools=80.9.0=pyhff2d567_0
  - snappy=1.2.2=h03e3b7b_0
  - sqlite=3.50.2=hb25bd0a_1
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=py311h06a4308_0
  - tbb=2021.13.0=hb60516a_3
  - tk=8.6.13=noxft_hd72426e_102
  - torchaudio=2.3.0=py311_cu121
  - typing_extensions=4.15.0=py311h06a4308_0
  - urllib3=2.5.0=py311h06a4308_0
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - array-record==0.8.1
      - asttokens==3.0.1
      - astunparse==1.6.3
      - attrs==25.3.0
      - av==15.1.0
      - beautifulsoup4==4.14.2
      - bitsandbytes==0.47.0
      - blessed==1.22.0
      - blinker==1.9.0
      - brotli==1.1.0
      - bypy==1.8.9
      - cachetools==6.2.2
      - click==8.3.0
      - cloudpickle==3.1.1
      - cmake==4.1.0
      - contourpy==1.3.3
      - crc32c==2.7.1
      - cycler==0.12.1
      - datasets==3.2.0
      - decorator==5.2.1
      - deepdiff==8.6.1
      - deepspeed==0.17.6
      - diffusers==0.34.0
      - dill==0.3.8
      - distro==1.9.0
      - dm-tree==0.1.9
      - docstring-parser==0.17.0
      - donfig==0.8.1.post1
      - dotenv==0.9.9
      - draccus==0.10.0
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - etils==1.13.0
      - evaluate==0.4.6
      - evdev==1.9.2
      - executing==2.2.1
      - farama-notifications==0.0.4
      - fastapi==0.117.1
      - ffmpy==0.6.1
      - flask==3.1.2
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - frozenlist==1.7.0
      - fsspec==2024.9.0
      - gast==0.6.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.43.0
      - google-genai==1.51.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.70.0
      - gpustat==1.1.1
      - gradio==5.47.1
      - gradio-client==1.13.2
      - groovy==0.1.2
      - grpcio==1.75.1
      - gymnasium==0.29.1
      - h11==0.16.0
      - h5py==3.14.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.10
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.1
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - immutabledict==4.2.1
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - inquirerpy==0.3.4
      - ipdb==0.13.13
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jiter==0.11.1
      - joblib==1.5.2
      - json-repair==0.53.0
      - jsonlines==4.0.0
      - keras==3.11.3
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lerobot==0.1.0
      - libclang==18.1.1
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - ml-dtypes==0.5.3
      - msgpack==1.1.1
      - msgpack-numpy==0.4.8
      - multidict==6.6.4
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - namex==0.1.0
      - ninja==1.13.0
      - nltk==3.9.2
      - numba==0.62.1
      - numcodecs==0.16.3
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - openai==2.6.1
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.17.0
      - orderly-set==5.5.0
      - orjson==3.11.3
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.5
      - pexpect==4.9.0
      - pfzy==0.3.4
      - piq==0.8.0
      - platformdirs==4.4.0
      - polars==1.35.1
      - polars-runtime-32==1.35.1
      - portalocker==3.2.0
      - promise==2.3
      - prompt-toolkit==3.0.52
      - propcache==0.3.2
      - protobuf==6.32.1
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.10
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pymunk==6.11.1
      - pynput==1.8.1
      - pyparsing==3.2.5
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - python-xlib==0.33
      - pytz==2025.2
      - pyyaml-include==1.4.1
      - pyzmq==27.1.0
      - qwen-vl-utils==0.0.14
      - regex==2025.9.18
      - requests-toolbelt==1.0.0
      - rerun-sdk==0.22.1
      - rich==14.1.0
      - rsa==4.9.1
      - ruff==0.13.2
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.39.0
      - shellingham==1.5.4
      - shtab==1.7.2
      - simple-parsing==0.1.7
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - starlette==0.48.0
      - sty==1.0.6
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorflow-datasets==4.9.9
      - tensorflow-metadata==1.17.2
      - termcolor==3.1.0
      - tf-keras==2.20.1
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - tiktoken==0.12.0
      - timeout-decorator==0.5.0
      - timm==1.0.20
      - tokenizers==0.21.4
      - toml==0.10.2
      - tomlkit==0.13.3
      - torch==2.7.1
      - torch-fidelity==0.3.0
      - torchcodec==0.5
      - torchmetrics==1.6.3
      - torchvision==0.22.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.49.0
      - triton==3.3.1
      - typeguard==4.4.4
      - typer==0.19.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tyro==0.9.35
      - tzdata==2025.2
      - uvicorn==0.37.0
      - validators==0.35.0
      - vlmeval==0.1.0
      - wandb==0.22.0
      - wcwidth==0.2.14
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - xlsxwriter==3.2.9
      - xxhash==3.5.0
      - yarl==1.20.1
      - zarr==3.1.3
      - zipp==3.23.0
prefix: 
  /data/yangyi/miniconda3/envs/metaquery_action
