_gradient_checkpointing: True
# vae_id: "Efficient-Large-Model/Sana_600M_512px_diffusers"
# noise_scheduler_id: "Efficient-Large-Model/Sana_600M_512px_diffusers"
# scheduler_id: "Efficient-Large-Model/Sana_600M_512px_diffusers"
# mllm_id: "Qwen/Qwen2.5-VL-3B-Instruct"
# diffusion_model_id: "Efficient-Large-Model/Sana_600M_512px_diffusers"

vae_id: "/data/yangyi/.cache/models/Sana_600M_512px_diffusers"
noise_scheduler_id: "/data/yangyi/.cache/models/Sana_600M_512px_diffusers"
scheduler_id: "/data/yangyi/.cache/models/Sana_600M_512px_diffusers"
mllm_id: "/data/yangyi/.cache/models/Qwen2.5-VL-3B-Instruct"
diffusion_model_id: "/data/yangyi/.cache/models/Sana_600M_512px_diffusers"

vae_downsample_f: 32
in_channels: 32
target_image_size: 512
wrist_image_size: 256
per_device_train_batch_size: 16
learning_rate: 0.0001
eval_steps: 1000
save_steps: 1000
warmup_steps: 5000
num_train_epochs: 2
lr_scheduler_type: "cosine_with_min_lr"
lr_scheduler_kwargs:
  min_lr: 0.000005
loss_type: "flow"
num_metaqueries: 9
modules_to_freeze:
  - "vae"
  - "model.mllm_backbone"
  - "model.transformer"
  - "model.connector"

modules_to_unfreeze:
  - "model.mllm_backbone.model.embed_tokens"
  - "model.policy_head"

connector_num_hidden_layers: 12
deepspeed: "configs/zero1.json"

train_datasets:
  droid: -1
eval_dataset: "droid"
dataset_root_dir: "/data/yangyi/datasets/droid_100_lerobot"

action_model_type: "DiT-L"
action_dim: 7
future_action_window_size: 4
past_action_window_size: 0
num_actqueries: 6
training_mode: "action"
max_timestep_gap: 6
num_gapqueries: 3

norm_stats_path: "/data/yangyi/metaquery_action_refactoring/configs/norm_stats.json"
unnorm_key: "droid"

save_part_checkpoints: True
resume_from_checkpoint: "/data/yangyi/metaquery_action_refactoring/whole_checkpoints/metaquery_action_droid/checkpoint-5000"
# resume_from_checkpoint: "/data/yangyi/metaquery_action_refactoring/whole_checkpoints/metaquery_image_ssv2_1to6/checkpoint-226000"
# resume_from_checkpoint: null